name: deckorator
description: Tools for creating card games
# version: 1.0.0
# homepage: https://www.example.com
# author: Jimmy Forrester-Fellowes <email@example.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  args: ^1.4.2
  csv: any
  # deckorator:
  #   path: ../deckorator
  pdf: any
  image: any
  http: any

dev_dependencies:
  pedantic: ^1.8.0
  test: any
