name: deckorator
description: Tools for creating card games and boardgames.
version: 3.0.0
homepage: https://github.com/jimmyff/deckorator

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  args: ^2.4.0
  csv: ^5.0.1
  pdf: ^3.10.1
  image: ^4.0.15
  http: ^0.13.5
  pool: ^1.5.1
  logging: ^1.2.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.2
